source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

#uby '2.6.8'
#ruby '2.7.0'
#ruby '3.0.0'
ruby '~> 3.0.0'
#ruby '~> 3.2.0'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'#, '~> 6.0.2', '>= 6.0.2.1'
# Use Puma as the app server
gem 'puma'#, '~> 4.1'
# Use SCSS for stylesheets
gem 'sass-rails'#, '>= 6'
#gem 'yarn' #no user, debe irse al sitio de yarn y luego copiar un  bin
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker'#, '~> 4.0' #errores relacionados con yarn, que no era tal, sino que falta un archivo en config. Webpacker.yml, el que finalmente lo consegui en algún forum
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks'#, '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'#, '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
#gem 'bootsnap', '>= 1.4.2', require: false

#logger
gem 'logging-email'
gem 'logging-rails'

#comercio
gem 'khipu-api-client'
gem 'paypal-sdk-rest'

#campañas
gem "dkim"
gem "haml-rails", "~> 2.0"

#acceso desde sitios autorizados
gem 'rack-cors', :require => 'rack/cors'


#profiling
gem 'memory_profiler'
gem 'get_process_mem'

#signed pdf
gem 'origami'
gem 'prawn'
gem 'prawn-table'
gem 'prawn-qrcode'

#para permitir el acceso como api
gem 'rest-client'#, '~> 1.8'


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'sqlite3', '~> 1.4'

  #integration tests

end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Use sqlite3 as the database for Active Record

  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'

  gem 'rexml'  
  gem 'factory_bot_rails'
  %w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
       gem lib, git: "https://github.com/rspec/#{lib}.git", branch: 'master' # Previously '4-0-dev' or '4-0-maintenance' branch
   end

end

#gancho está en production en gancho.alectrico.cl y en aelecrico.cl
group :production, :aelectrico do
  gem 'pg'
  gem 'rexml'

end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
#gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
